const data = [
    { title: '패턴', postBoard: '밥친구', postNumber: 1 , postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: '마음가짐', postBoard: '맛집', postNumber: 2, postWriter: 'qwer', postDate: '23-06-02', postView: 20 },
    { title: 'HTML 기초', postBoard: '자랑', postNumber: 3, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: 'css 기초', postBoard: '꿀팁', postNumber: 4, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: 'CSSflex', postBoard: '자랑',postNumber: 5, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: 'Mac 계산기 클론하기', postBoard: '자유', postNumber: 6, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: 'CSS grid', postBoard: '자유',postNumber: 7, postWriter: 'qwer', postDate: '23-06-02', postView: 20 },
    { title: 'slice? splice', postBoard: '맛집', postNumber: 8, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: '함수를 정의하는 방법', postBoard: '꿀팁',postNumber: 9, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: '순열(Permutation) 구현하기', postBoard: '맛집', postNumber: 10, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: '문자열에서 특정 위치의 문자를 변경하고 싶은 경우', postBoard: '자랑',postNumber: 11, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: 'letIt const', postBoard: '나눔', postNumber: 12, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: 'nvm', postBoard: '홍보', postNumber: 13, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: '요소 노드의 텍스트 조작하기(nodeValue, textContent, innerHTML)', postBoard: '비추', postNumber: 14, postWriter: 'abcd', postDate: '23-06-01', postView: 30 },
    { title: '자바스크립트의 배열은 배열이 아니다!', postBoard: '밥친구', postNumber: 15, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: 'JSON 다루기(JSON.parse), JSON.stringify())', postBoard: '맛집', postNumber: 16,  postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: '원시 자료형과 참조 자료형', postBoard: '꿀팁',postNumber: 17, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: '[]===[]는 왜 false인가', postBoard: '꿀팁',postNumber: 18, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: 'this (동적 바인딩)', postBoard: '맛집', postNumber: 19, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: '유효성 검사를 포함한 간단한 회원가입 폼 페이지 만들기', postBoard: '자유', postNumber: 20,  postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: '#fff와 #ffffff', postBoard: '자랑',postNumber: 21, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: '안다고 생각했지만, 헷갈렸던 문법들', postBoard: '자유', postNumber: 22, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: 'DOM이 뭔가요?', postBoard: '비추', postNumber: 23, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: '영화 좌석 예약 페이지 만들기 ', postBoard: '꿀팁', postNumber: 24, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: '테두리가 두 줄처럼 보이는 경우 (border)', postBoard: '맛집', postNumber: 25, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: 'IS0 형식의 날짜(yyyy-mm-ddThh:mm:ssz)를 현재 위치 시간대로 변경하기 # ', postBoard: '맛집', postNumber: 26, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
    { title: '페이지네이션', postBoard: '밥친구', postNumber: 27, postWriter: 'zxcv', postDate: '23-06-31', postView: 100 },
  ];

//   제목 등 내용 불러와서 최신순으로 리스트에 넣기